---

- hosts: webservers
  tasks:
    - name: Install pip
      apt: name=python-pip state=present
    - name: install docker-py package
      pip: name=docker-py
      
    - name: delete container if exist
      docker_container:
        name: "{{ server_name }}
        image: "aronaba/mywebserver:v1"
        state: absent
      
    - name: Running the container
      docker_container:
        name:  "{{ server_name }}""
        image: "aronaba/mywebserver:v1"
        volumes:
          - "/home/docker/vol_shared:/data"
        ports:
          - " {{ access_port }}:{{ http_port_expose }} "
        state: started
  become: true 
      